# Generated by Django 3.2.4 on 2021-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='booking_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата бронирования'),
        ),
    ]
