# Generated by Django 3.2.4 on 2021-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0002_alter_place_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='type',
            field=models.CharField(choices=[('Classic', 'Классический'), ('Open', 'Открытый'), ('Mixed', 'Смешанный'), ('Old', 'Старой постройки')], default=None, max_length=100, verbose_name='Тип офиса'),
        ),
    ]
