# Generated by Django 3.2.4 on 2021-06-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0003_office_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/', verbose_name='Изображение офиса'),
        ),
    ]
