# Generated by Django 3.2.4 on 2021-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0004_office_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='need_to_build_empty_places',
            field=models.BooleanField(default=False, verbose_name='Нужно ли создать пустые места?'),
        ),
    ]
