# Generated by Django 3.2.4 on 2021-06-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0005_room_need_to_build_empty_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='title',
            field=models.CharField(default='Неизвестная компания', max_length=150, verbose_name='Компания в офисе'),
        ),
    ]
